### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by jlag34** [Glorian305/f1-3-c2p1-colmar-academy#4]
You did a good job with your project. Your code looked really good. Great job using lots of different styles to get your final result. Also, looks like you did a good job mastering media queries. Your page looks good with most sizes but needs a little polish with others because of the font-size. One thing that I would have liked to see if extra effort with color and effects. Some areas had a lot of color while some didn't at all (the colors seemed almost a little random). All in all, nice job with this one. Keep up the good work!

**Comment by Glorian305** [comment]
Thank you for your review!
The Capstone project was the hardest project so far but on the bright side really helped me test my skills and learn some new skills as well.
Struggled a bit in this unit too.
But some new lessons in unit 9 like bootstrap helped a lot.
I will practice more and be more “colorful “ haha,didn’t really want to dare but i guess that’s the whole point of being a developer,to be Daring.Thanks again!

**Comment by Glorian305** [comment]
Thank you for your review!
The Capstone project was the hardest project so far but on the bright side really helped me test my skills and learn some new skills as well.
Struggled a bit in this unit too.
But some new lessons in unit 9 like bootstrap helped a lot.
I will practice more and be more “colorful “ haha,didn’t really want to dare but i guess that’s the whole point of being a developer,to be Daring.Thanks again!
